"""auto

Revision ID: 0f800caf5804
Revises: 
Create Date: 2020-08-04 03:00:05.606137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f800caf5804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('firebase_user_id', sa.String(), nullable=True),
    sa.Column('chores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fish', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bugs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dive', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('firebase_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
