"""added firebase_user_id to table

Revision ID: 599228e21d6b
Revises: 8e99d936d159
Create Date: 2020-08-03 22:22:02.239657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599228e21d6b'
down_revision = '8e99d936d159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('firebase_user_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'inventory', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'firebase_user_id')
    # ### end Alembic commands ###
